export const propiedades = [
  {
    nombre: "Cabaña Acogedora en el Bosque",
    descripcion: "Una cabaña encantadora rodeada de naturaleza, ideal para un descanso reparador. Aquí podrás disfrutar del aire fresco y la tranquilidad del bosque, un lugar perfecto para desconectar del estrés diario.\n\nImagina despertarte con el canto de los pájaros y disfrutar de una taza de café en el porche. La cabaña ofrece un ambiente mágico, donde cada amanecer es un regalo y cada atardecer se convierte en una obra de arte.",
    habitaciones: "3",
    estacionamientos: "2",
    wc: "1",
    calle: "Calle Morelos",
    lat: "18.8030",
    lng: "-98.9495",
    imagen: "1.jpg",
    publicado: true,
    precioId: 1,
    categoriaId: 2,
    usuarioId: 1
  },
  {
    nombre: "Apartamento Moderno en el Centro",
    descripcion: "Un elegante apartamento con vistas impresionantes de la ciudad. Perfecto para quienes buscan un hogar vibrante en el corazón de la ciudad, donde la comodidad y el estilo se fusionan.\n\nDisfruta de la vida urbana con todas las comodidades modernas a tu alcance. Ideal para disfrutar de cenas con amigos o relajarte después de un largo día, este apartamento es el espacio ideal para vivir la ciudad al máximo.",
    habitaciones: "2",
    estacionamientos: "1",
    wc: "2",
    calle: "Calle Miguel Hidalgo",
    lat: "18.8041",
    lng: "-98.9498",
    imagen: "2.jpg",
    publicado: true,
    precioId: 2,
    categoriaId: 3,
    usuarioId: 1
  },
  {
    nombre: "Villa Frente al Mar",
    descripcion: "Esta lujosa villa ofrece acceso directo a la playa y vistas espectaculares al océano. Es el refugio perfecto para disfrutar de un estilo de vida exclusivo, donde cada día puede ser una nueva aventura bajo el sol.\n\nImagínate relajándote junto a la piscina o disfrutando de una cena al atardecer en la terraza. Este lugar es ideal para los amantes del mar y aquellos que buscan un escape de la rutina diaria.",
    habitaciones: "5",
    estacionamientos: "3",
    wc: "4",
    calle: "Calle Cuautla",
    lat: "18.8028",
    lng: "-98.9302",
    imagen: "3.jpg",
    publicado: true,
    precioId: 4,
    categoriaId: 1,
    usuarioId: 1
  },
  {
    nombre: "Casa Familiar Espaciosa",
    descripcion: "Un hogar amplio con un gran jardín, ideal para familias. Disfruta de espacios diseñados para crear recuerdos inolvidables y compartir momentos especiales en un ambiente seguro.\n\nCada rincón está pensado para ofrecer comodidad y funcionalidad, donde los niños pueden jugar libremente y los adultos pueden relajarse al aire libre. Este es el lugar perfecto para que tu familia florezca.",
    habitaciones: "4",
    estacionamientos: "2",
    wc: "3",
    calle: "Calle José María Morelos",
    lat: "18.7995",
    lng: "-98.9341",
    imagen: "4.jpg",
    publicado: true,
    precioId: 2,
    categoriaId: 3,
    usuarioId: 1
  },
  {
    nombre: "Penthouse de Lujo",
    descripcion: "Este penthouse cuenta con acabados de alta gama y una terraza privada impresionante, perfecta para disfrutar de las vistas de la ciudad. Es el espacio ideal para vivir con estilo y confort.\n\nAquí, cada rincón ha sido diseñado para brindar una experiencia de vida única, donde el lujo y la funcionalidad se combinan para crear un hogar excepcional. Ideal para quienes buscan lo mejor en la vida urbana.",
    habitaciones: "3",
    estacionamientos: "2",
    wc: "3",
    calle: "Calle 5 de Febrero",
    lat: "18.8038",
    lng: "-98.9403",
    imagen: "5.jpg",
    publicado: true,
    precioId: 5,
    categoriaId: 4,
    usuarioId: 1
  },
  {
    nombre: "Estudio Encantador",
    descripcion: "Un estudio acogedor con comodidades modernas, ideal para solteros o parejas. Disfruta de un espacio práctico y funcional, diseñado para maximizar tu comodidad y estilo de vida.\n\nCon una ubicación perfecta, este estudio te permitirá vivir cerca de todas las atracciones de la ciudad, mientras te brinda un refugio acogedor al final del día. El lugar ideal para disfrutar de la vida urbana con un toque personal.",
    habitaciones: "1",
    estacionamientos: "0",
    wc: "1",
    calle: "Calle Juan Escutia",
    lat: "18.8012",
    lng: "-98.9424",
    imagen: "6.jpg",
    publicado: true,
    precioId: 7,
    categoriaId: 4,
    usuarioId: 1
  },
  {
    nombre: "Casa de Campo Rústica",
    descripcion: "Esta casa de campo ofrece amplio terreno y un entorno pacífico, ideal para desconectar y disfrutar de la naturaleza. Un lugar perfecto para escapadas familiares y momentos de tranquilidad.\n\nImagínate disfrutando de barbacoas al aire libre o explorando senderos naturales. Este espacio es ideal para que los niños jueguen y los adultos se relajen, creando recuerdos inolvidables en cada rincón.",
    habitaciones: "4",
    estacionamientos: "4",
    wc: "2",
    calle: "Calle Francisco Villa",
    lat: "18.8000",
    lng: "-98.9467",
    imagen: "7.jpg",
    publicado: true,
    precioId: 8,
    categoriaId: 2,
    usuarioId: 1
  },
  {
    nombre: "Loft Urbano Moderno",
    descripcion: "Un loft moderno con un diseño abierto y estilo industrial, ideal para quienes buscan un espacio único y dinámico en la ciudad. Perfecto para artistas y creativos que desean un hogar que inspire su trabajo.\n\nCada detalle ha sido pensado para maximizar la luz y el espacio, creando un ambiente vibrante y acogedor. Este es el lugar ideal para vivir y trabajar en un entorno que estimula la creatividad.",
    habitaciones: "2",
    estacionamientos: "1",
    wc: "1",
    calle: "Calle Pino Suárez",
    lat: "18.8020",
    lng: "-98.9445",
    imagen: "8.jpg",
    publicado: true,
    precioId: 9,
    categoriaId: 2,
    usuarioId: 1
  },
  {
    nombre: "Casa Elegante en el Barrio",
    descripcion: "Esta townhouse elegante se encuentra en un vecindario deseable, ofreciendo múltiples amenidades y un ambiente acogedor. Perfecta para disfrutar de la vida urbana con estilo y comodidad.\n\nCon espacios bien diseñados y un ambiente cálido, es el lugar ideal para crear un hogar lleno de vida y felicidad. Cada rincón invita a disfrutar de momentos especiales en familia y amigos.",
    habitaciones: "3",
    estacionamientos: "2",
    wc: "2",
    calle: "Calle Galeana",
    lat: "18.8049",
    lng: "-98.9490",
    imagen: "9.jpg",
    publicado: true,
    precioId: 10,
    categoriaId: 1,
    usuarioId: 1
  },
  {
    nombre: "Casa de Lago Hermosa",
    descripcion: "Esta hermosa casa ofrece vistas al lago y un muelle privado, perfecta para disfrutar de la paz y la serenidad que brinda el agua. Un refugio ideal para aquellos que aman la naturaleza.\n\nImagina despertar cada día con la brisa del lago y el canto de las aves, creando un ambiente relajante. Aquí podrás disfrutar de momentos inolvidables en familia y amigos, rodeado de belleza natural.",
    habitaciones: "4",
    estacionamientos: "3",
    wc: "3",
    calle: "Calle Prolongación Guerrero",
    lat: "18.7980",
    lng: "-98.9310",
    imagen: "10.jpg",
    publicado: true,
    precioId: 6,
    categoriaId: 4,
    usuarioId: 1
  },
  {
    nombre: "Mansión Histórica",
    descripcion: "Una mansión grandiosa que combina encanto histórico con actualizaciones modernas. Ideal para quienes buscan un hogar con carácter y estilo único.\n\nCada habitación cuenta una historia, mientras que las comodidades contemporáneas garantizan una vida confortable y lujosa. Este es el lugar perfecto para vivir en grande y disfrutar de una vida plena.",
    habitaciones: "6",
    estacionamientos: "5",
    wc: "5",
    calle: "Calle 10 de Abril",
    lat: "18.8044",
    lng: "-98.9335",
    imagen: "11.jpg",
    publicado: true,
    precioId: 8,
    categoriaId: 1,
    usuarioId: 1
  },
  {
    nombre: "Condominio Contemporáneo",
    descripcion: "Un condominio moderno en un edificio de gran altura, con excelentes amenidades. Perfecto para quienes buscan una vida urbana con estilo y comodidad.\n\nCada detalle está diseñado para ofrecer el máximo confort y una vista impresionante de la ciudad. Este espacio es ideal para disfrutar de la vida en el corazón de la metrópoli, rodeado de todo lo que necesitas.",
    habitaciones: "2",
    estacionamientos: "1",
    wc: "2",
    calle: "Calle Cuauhtémoc",
    lat: "18.8050",
    lng: "-98.9350",
    imagen: "12.jpg",
    publicado: true,
    precioId: 4,
    categoriaId: 1,
    usuarioId: 1
  },
  {
    nombre: "Retiro en Cabaña Encantadora",
    descripcion: "Una pequeña cabaña encantadora, perfecta para una escapada de fin de semana. Disfruta de la tranquilidad de la naturaleza y el confort de un hogar acogedor.\n\nEste espacio es ideal para desconectar del ajetreo diario y disfrutar de momentos de paz. Con todo lo necesario para una escapada perfecta, esta cabaña te espera para crear recuerdos inolvidables.",
    habitaciones: "2",
    estacionamientos: "1",
    wc: "1",
    calle: "Calle Ignacio Allende",
    lat: "18.8040",
    lng: "-98.9405",
    imagen: "13.jpg",
    publicado: true,
    precioId: 9,
    categoriaId: 2,
    usuarioId: 1
  },
  {
    nombre: "Dúplex Estiloso",
    descripcion: "Un dúplex moderno con entrada privada y patio, ideal para disfrutar de un espacio personal en un vecindario vibrante. Perfecto para familias o grupos que buscan comodidad y estilo.\n\nCon espacios amplios y luminosos, este hogar es ideal para vivir y disfrutar. La combinación de diseño contemporáneo y funcionalidad lo convierte en un lugar perfecto para llamar hogar.",
    habitaciones: "3",
    estacionamientos: "2",
    wc: "2",
    calle: "Calle 16 de Septiembre",
    lat: "18.8033",
    lng: "-98.9442",
    imagen: "14.jpg",
    publicado: true,
    precioId: 9,
    categoriaId: 3,
    usuarioId: 1
  },
  {
    nombre: "Villa de Resort Lujosa",
    descripcion: "Una villa de estilo resort con piscina y spa, perfecta para disfrutar de momentos de relajación y diversión. Ideal para familias o grupos que buscan escapar de la rutina y sumergirse en un entorno de lujo y confort.\n\nAquí cada día se siente como unas vacaciones, donde la tranquilidad y la diversión van de la mano. Disfruta de cada rincón de esta villa y crea recuerdos inolvidables con tus seres queridos.",
    habitaciones: "4",
    estacionamientos: "3",
    wc: "4",
    calle: "Calle del Sol",
    lat: "18.8031",
    lng: "-98.9409",
    imagen: "15.jpg",
    publicado: true,
    precioId: 10,
    categoriaId: 2,
    usuarioId: 1
  },
  {
    nombre: "Loft Chic",
    descripcion: "Un loft moderno y chic en una zona vibrante, perfecto para quienes buscan un estilo de vida dinámico. Disfruta de un diseño contemporáneo y funcional, donde cada detalle ha sido cuidadosamente pensado para maximizar el confort y la estética.\n\nEste espacio no solo es un hogar, sino una fuente de inspiración que se adapta a tu estilo de vida. Ideal para quienes desean vivir en el centro de la acción, rodeados de cultura y creatividad.",
    habitaciones: "1",
    estacionamientos: "0",
    wc: "1",
    calle: "Calle Cañón del Sumidero",
    lat: "18.8008",
    lng: "-98.9346",
    imagen: "16.jpg",
    publicado: true,
    precioId: 4,
    categoriaId: 4,
    usuarioId: 1
  },
  {
    nombre: "Gran Hacienda",
    descripcion: "Una magnífica hacienda con amplios terrenos y diseño elegante. Este espacio es ideal para disfrutar de la vida en un ambiente exclusivo, rodeado de belleza natural y serenidad.\n\nUn lugar donde cada rincón invita a crear momentos inolvidables con familia y amigos. Disfruta de la tranquilidad de la vida campestre sin sacrificar la comodidad moderna.",
    habitaciones: "7",
    estacionamientos: "6",
    wc: "6",
    calle: "Calle 1 de Mayo",
    lat: "18.8048",
    lng: "-98.9318",
    imagen: "17.jpg",
    publicado: true,
    precioId: 8,
    categoriaId: 5,
    usuarioId: 1
  }
];